application: geochicagodata
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: main.py

builtins:
- deferred: on
